window.WEDDING_THEMES={
 deepBlue:{background:"#F4F6FA",surface:"#FFFFFF",surfaceAlt:"#E2EAF5",text:"#132A42",muted:"#5C7086",accent:"#245D9C",accentDark:"#123B6D",accentSoft:"#D4E2F2",warm:"#B99A76",line:"#CCD9E7",heroText:"#FFFFFF"},
 sage:{background:"#F5F2EC",surface:"#FFFDF9",surfaceAlt:"#E9EEE9",text:"#25302A",muted:"#68736C",accent:"#718274",accentDark:"#425247",accentSoft:"#DCE4DC",warm:"#B28B70",line:"#D9DDD8",heroText:"#FFFFFF"}
};
window.WEDDING_CONFIG={
 themePreset:"deepBlue",
 fonts:{title:'"Cormorant Garamond", Georgia, serif',body:'"Manrope", Arial, sans-serif'},
 couple:{firstName:"Liliane",secondName:"Igor",initials:"L · I",signature:"Com amor, Liliane & Igor"},
 wedding:{dateISO:"2027-04-24T19:00:00-03:00",endISO:"2027-04-24T23:30:00-03:00",longDate:"24 de Abril de 2027",shortDate:"24 · 04 · 2027",weekday:"Sábado",day:"24",month:"Abril",year:"2027",time:"19h00",city:"Itu · São Paulo"},
 opening:{enabled:true,eyebrow:"Você recebeu um convite especial",title:"Queremos celebrar este dia com você.",hint:"Um capítulo importante da nossa história está prestes a começar.",buttonLabel:"Abrir convite",guestQueryParam:"convidado",guestPrefix:"Convite destinado a"},
 hero:{image:{desktop:"assets/images/hero.webp",mobile:"assets/images/hero.webp"},eyebrow:"Save the date",title:"",subtitle:"Uma celebração de amor, encontros e novos começos.",primaryButton:"Confirmar presença",secondaryButton:"Ver detalhes"},
 welcome:{eyebrow:"Nosso convite",title:"Um dia para guardar na memória.",text:"Depois de tantos caminhos compartilhados, chegou o momento de abrirmos um novo capítulo. Queremos viver esse dia ao lado das pessoas que fizeram parte da nossa história — e você é uma delas."},
 story:{enabled:true,pretitle:"1 João 4:19",phrase:"Nós amamos porque ele nos amou primeiro.",eyebrow:"Nossa história",title:"O sem planos, virou cem planos...",image:{desktop:"assets/images/story.webp",mobile:"assets/images/story.webp"},year:"desde 2022",paragraphs:["Tudo começou sem grandes planos, em uma festa, através de um amigo que nos apresentou. Naquele momento, nenhum de nós poderia imaginar que aquele encontro daria início a uma história que chegaria tão longe.","Entre conversas, encontros e momentos compartilhados, fomos nos conhecendo e descobrindo que aquele acaso tinha, na verdade, um propósito muito maior.","O que começou sem grandes expectativas se transformou em amor, companheirismo e em uma vontade de construir juntos uma vida inteira.","Hoje, depois de tantos momentos vividos lado a lado, escolhemos dar o passo mais importante da nossa história: dizer “sim” um ao outro diante de Deus e das pessoas que amamos."],quote:"Sem planejar o começo, encontramos um no outro o futuro que queremos viver."},
 details:{eyebrow:"Onde & quando",title:"Tudo o que você precisa para celebrar conosco."},
 events:[
  {label:"Cerimônia",time:"19h00 · chegar às 18h30",venue:"Paróquia São Luís Gonzaga",address:"R. Leonardo Piunti, 475 — São Luiz, Itu — SP, 13304-250",mapsUrl:"https://maps.app.goo.gl/cBcnP7PYY2Ed3Zdf9",mapsLabel:"Abrir no mapa",image:{desktop:"assets/images/paroquia.webp",mobile:"assets/images/paroquia.webp"}},
  {label:"Recepção",time:"Te aguardamos aqui, após a cerimônia",venue:"Buffet Encanto",address:"Av. Walter Nardelli, 1074 — Jardim Guarujá, Salto — SP, 13323-260",mapsUrl:"https://maps.app.goo.gl/nietYBWBGj9y7Lm67",mapsLabel:"Como chegar",image:{desktop:"assets/images/buffet.webp",mobile:"assets/images/buffet.webp"}}
 ],
 schedule:{enabled:true,eyebrow:"Programação",title:"O roteiro do nosso dia",note:"Os horários podem receber pequenos ajustes conforme o andamento da celebração.",backgroundImage:{desktop:"assets/images/gallery-2.webp",mobile:"assets/images/gallery-2.webp"},items:[
  {time:"18:30",title:"Boas-vindas",text:"Chegue com calma e encontre seu lugar.",image:{desktop:"assets/images/gallery-1.webp",mobile:"assets/images/gallery-1.webp"}},
  {time:"19:00",title:"Cerimônia",text:"O momento do nosso sim.",image:{desktop:"assets/images/story.webp",mobile:"assets/images/story.webp"}},
  {time:"20:30",title:"Recepção",text:"Brindes, encontros e celebração.",image:{desktop:"assets/images/gallery-4.webp",mobile:"assets/images/gallery-4.webp"}},
  {time:"21:30",title:"Jantar",text:"Um momento preparado para compartilhar à mesa.",image:{desktop:"assets/images/gallery-5.webp",mobile:"assets/images/gallery-5.webp"}},
  {time:"22:00",title:"Pista aberta",text:"Hora de comemorar sem pressa.",image:{desktop:"assets/images/gallery-3.webp",mobile:"assets/images/gallery-3.webp"}}
 ]},
 gallery:{enabled:true,eyebrow:"Memórias",title:"Alguns capítulos antes do grande dia.",images:[1,2,3,4,5].map((n)=>({src:{desktop:`assets/images/gallery-${n}.webp`,mobile:`assets/images/gallery-${n}.webp`},alt:"Foto do casal",caption:`Capítulo 0${n}`}))},
 dressCode:{enabled:true,eyebrow:"Dress code",title:"Traje Esporte fino",text:"Elegância e conforto para celebrar conosco. Blazer e gravata não são necessários, assim como vestido longo para as mulheres.",note:"Pedimos gentilmente que branco e azul-marinho não sejam utilizados, pois essas cores estarão reservadas para a composição do casamento.",image:{desktop:"assets/images/dress-code.webp",mobile:"assets/images/dress-code.webp"},palette:["#3F4C39","#7A8469","#B8A58B","#C9B8A4","#4F3931"]},
 guestInfo:{enabled:true,eyebrow:"Para você se organizar",title:"Informações importantes",items:[{icon:"car",title:"Estacionamento",text:"Há vagas próximo ao local. Se for beber, considere táxi ou aplicativo."},{icon:"clock",title:"Pontualidade",text:"A cerimônia começa às 19h00. Recomendamos chegar com 30 minutos de antecedência."},{icon:"camera",title:"Fotos",text:"Registre e compartilhe os momentos, mantendo o corredor livre durante a cerimônia."}]},
 faq:{enabled:true,eyebrow:"Dúvidas frequentes",title:"Antes do grande dia",items:[{question:"Posso levar acompanhante?",answer:"Consideraremos apenas os nomes indicados no convite. Caso exista acompanhante liberado, essa informação pode ser combinada com os noivos."},{question:"Até quando preciso confirmar presença?",answer:"Pedimos que a confirmação seja feita até 10 de Março de 2027 para facilitar a organização do evento."},{question:"A cerimônia e a recepção são no mesmo local?",answer:"Não. A cerimônia será na Paróquia São Luís Gonzaga e a recepção será no Buffet Encanto."},{question:"Vai ter estacionamento?",answer:"Sim. Porém, as vagas situam-se na rua próximo ao local da festa."}]},
 gifts:{title:"Lista de presentes",intro:"Sua presença é o maior presente. Se quiser contribuir com nossos planos, conheça nossa lista."},
 rsvp:{enabled:true,eyebrow:"Confirmação de presença",title:"Você vem celebrar com a gente?",text:"Sua resposta é muito importante para organizarmos cada detalhe com carinho.",deadline:"10 de Março de 2027",buttonLabel:"Enviar confirmação",mode:"whatsapp",whatsappNumber:"5511956766105",formAction:"",successMessage:"Obrigada! Sua confirmação foi recebida.",maxGuestsDefault:4,guestLimitQueryParam:"lugares",baseMessage:"Olá! Estou respondendo ao convite de casamento de Liliane e Igor e confirmo minha presença."},
 music:{enabled:false,file:"",volume:.55,labelPlay:"Tocar música",labelPause:"Pausar música"},
 guestSystem:{enabled:true,mode:"api",tokenQueryParam:"convite",endpoint:"https://oblucxwvsouyjhfqaten.supabase.co/functions/v1/invite-public",demoInvites:{"DEMO-FAMILIA-SILVA":{displayName:"Família Silva",seats:4,members:["João Silva","Maria Silva","Pedro Silva","Ana Silva"]}}},
 images:{rsvp:{desktop:"assets/images/rsvp.webp",mobile:"assets/images/rsvp.webp"}},
 footer:{text:"Esperamos você para celebrar este capítulo com a gente."}
};